Features
Obimbo07/Hello-Microverse pull request #1
Opened 2023-04-26 21:55 UTC by Obimbo07

2023-04-26 22:09 UTC, hiromataba requested changes
Hi @Obimbo07     :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- You added a .gitignore file  :+1: 
- You have good commit messages :heavy_check_mark:  
- Good Gitflow :rocket: 

## Required Changes ♻️

- [ ] Your Pull Request should have a descriptive title telling you what changes are inside 😉 

- [ ] Your Pull Request should have a summary describing introduced changes in more detail
 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 22:09 UTC, hiromataba commented on  .github/workflows/linters.yml
> +
- [ ] Linting is a great tool to help you fix errors in your code so it is better to set them up, have a look at the Microverse [Linters](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjJxayZ5cb-AhWAXaQEHeqZBpUQFnoECA8QAQ&url=https%3A%2F%2Fgithub.com%2Fmicroverseinc%2Flinters-config&usg=AOvVaw0Ek5AHhllFIJq-syhCrMx3) configuration and please do not modify the linters, your linters are not running on GitHub please double check that

2023-04-26 22:09 UTC, hiromataba commented on test.md
> +This file should be ignored by git
- [ ] Your `test.md` file should be ignore meaning that it should be put in the `.gitignore` file

2023-04-26 22:09 UTC, hiromataba commented on README.md
> + - Twitter [@austsine](https://twitter.com/austsine)
-  [ ] Please use the [Microverse](https://github.com/microverseinc/readme-template) README template for you project as required 😉

2023-04-27 04:41 UTC, AdnanOlarmmi requested changes
Hi @Obimbo07, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Professional Readme.
- Nice work ignoring appropriate files.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 04:41 UTC, AdnanOlarmmi commented on  .github/workflows/linters.yml
> +
> * [ ]  Linting is a great tool to help you fix errors in your code so it is better to set them up, have a look at the Microverse [Linters](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjJxayZ5cb-AhWAXaQEHeqZBpUQFnoECA8QAQ&url=https%3A%2F%2Fgithub.com%2Fmicroverseinc%2Flinters-config&usg=AOvVaw0Ek5AHhllFIJq-syhCrMx3) configuration and please do not modify the linters, your linters are not running on GitHub please double check that

- [ ] Just like the previous reviewer said above, you've added the linter.yml in the workflows directory, which is correct. Kindly follow through all the instructions on the page, to have an optimal setup. This will ensure your code follow the required and best practices 😉

2023-04-27 04:41 UTC, AdnanOlarmmi commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Currently your license file isn't linking anywhere, Kindly add an appropriate license, whether linking to the license page or adding the license file to your repo and linking it in the readme file, this will make your work very professional 

<img width="773" alt="image" src="https://user-images.githubusercontent.com/41163571/234760652-9a0aa016-8ceb-4244-9e25-6d8fba285461.png">

2023-04-27 16:31 UTC, vickymarz requested changes
Hi @Obimbo07, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 16:31 UTC, vickymarz commented on  .github/workflows/linters.yml
> +name: Linters
- [ ] You have tried to implement the required changes, but the issue is that the linters workflows is not running linter chrcks on your pull request. You are expected to have green check mark to show that your linters are working and passed. Please check your linters setup properly to be sure you are not missing any details 👍🏽

2023-04-27 16:51 UTC, AbayomiOlaoye requested changes
Hi @Obimbo07 :wave:, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)

 ## Highlights
- Good PR message ✅ 
- Great commit messages ✅ 
- Features are implemented well :heavy_check_mark: 
- Fair attempt at ReadMe customization :heavy_check_mark: 

 ## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 16:51 UTC, AbayomiOlaoye commented on README.md
> +  - [🚀 Live Demo](#live-demo)
- [ ] [OPTIONAL] Great job with this descriptive repo that makes your repo looks really professional :muscle: My opinion with this `live demo` here is that if your page is not deployed already, you don't have to include it in your project. And since this is not deployed live yet, it will be great to remove it to avoid giving users unintended impressions which may not be so favorable. :wink:

2023-04-27 16:51 UTC, AbayomiOlaoye commented on README.md
> + - Live Demo coming soon
- [ ] [OPTIONAL] As we agreed in the previous comment, to avoid your work space looking more like a template or an unplanned piece, it is better to avoid adding this section if the content is not ready. Kindly consider removing this, and adding it whenever you deployed the page using any service of your choice :+1:

2023-04-27 16:51 UTC, AbayomiOlaoye commented on README.md
> +
- [ ] [OPTIONAL] Looking at your table of contents, I am not sure that I saw this as part of what I should look forward to seeing in your ReadMe. This is probably because it wasn't important, after all! Did you also notice that this doesn't form part of the approved format/template by Microverse? In my opinion, regarding your usage, I think it's a repetition of what the `Authors` section is all about, and this is not a good practice in programming or web development. You might consider removing it or not adding it to other future projects.

2023-04-27 16:51 UTC, AbayomiOlaoye commented on  .github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
- [ ] I am sorry to see you struggle with Linter this much but do not worry, you will soon get hold of it :pleading_face: I am sure of that! Linter allows you to code following certain conventions or generally accepted coding standards which are part of the experience you will be exposed to in real life working environment. It allows a considerable amount of uniformity, maintainability, scalability, understandability, and some elements of continuity with other developers' code since you will be working in a team.
- So, please let's give this a shot again - maybe this time will be great :muscle: 
  - [ ] According to my previous colleagues suggestion, kindly follow [this tutorial](https://github.com/microverseinc/linters-config/tree/master/html-css) step-by-step again (except that in addition to having `/node_modules` in the `.gitignore` file, you should have `test.md` there too as you do now).
  - [ ] It will help to run necessary files from your command line so that important files and dependencies can be added into your project which will allow your linter to run.

- _This is what you have now (the green tick is missing):_

![image](https://user-images.githubusercontent.com/99715640/234933107-4989e4df-bc1e-410f-b1f5-29c7e6dc4be9.png)

2023-05-01 08:12 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 08:18 UTC, merged